db = db.getSiblingDB("ecommerce");

const sampleProducts = [
  // Electronics
  {
    name: "MacBook Pro 16",
    description: "Laptop Apple M2 Pro, 16GB RAM, 512GB SSD",
    price: 2499.99,
    category: "electronics",
    stock: 10,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "iPhone 15 Pro",
    description: "Smartphone Apple A17 Pro, 256GB",
    price: 1199.99,
    category: "electronics",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung QLED 4K TV",
    description: '65" Smart TV con HDR',
    price: 1299.99,
    category: "electronics",
    stock: 8,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sony PlayStation 5",
    description: "Consola de videojuegos de última generación",
    price: 499.99,
    category: "electronics",
    stock: 12,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "iPad Air",
    description: "Tablet Apple M1, 64GB",
    price: 599.99,
    category: "electronics",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Dell XPS 13",
    description: "Laptop ultradelgada con Intel i7",
    price: 1299.99,
    category: "electronics",
    stock: 10,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "AirPods Pro",
    description: "Auriculares inalámbricos con cancelación de ruido",
    price: 249.99,
    category: "electronics",
    stock: 25,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "Último modelo de Samsung con IA integrada",
    price: 1299.99,
    category: "electronics",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Nintendo Switch OLED",
    description: "Consola híbrida con pantalla OLED",
    price: 349.99,
    category: "electronics",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Canon EOS R6",
    description: "Cámara mirrorless profesional",
    price: 2499.99,
    category: "electronics",
    stock: 8,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Books
  {
    name: "Cien años de soledad",
    description: "Obra maestra de Gabriel García Márquez",
    price: 19.99,
    category: "books",
    stock: 50,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "1984",
    description: "Clásico distópico de George Orwell",
    price: 15.99,
    category: "books",
    stock: 40,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "El Principito",
    description: "Libro ilustrado de Antoine de Saint-Exupéry",
    price: 12.99,
    category: "books",
    stock: 60,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Don Quijote de la Mancha",
    description: "Obra cumbre de Miguel de Cervantes",
    price: 24.99,
    category: "books",
    stock: 30,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Harry Potter Saga Completa",
    description: "Colección de 7 libros de J.K. Rowling",
    price: 99.99,
    category: "books",
    stock: 25,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Clothing
  {
    name: "Chaqueta de Cuero",
    description: "Chaqueta de cuero genuino para hombre",
    price: 199.99,
    category: "clothing",
    stock: 25,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Vestido de Noche",
    description: "Vestido elegante para ocasiones especiales",
    price: 149.99,
    category: "clothing",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Jeans Premium",
    description: "Jeans de alta calidad, corte regular",
    price: 89.99,
    category: "clothing",
    stock: 30,
    images: ["/images/product-ph.png"],
    rating: 4.4,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Abrigo de Invierno",
    description: "Abrigo largo con forro térmico",
    price: 179.99,
    category: "clothing",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Zapatos Deportivos",
    description: "Zapatillas para running con amortiguación",
    price: 129.99,
    category: "clothing",
    stock: 40,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Camisa de Lino",
    description: "Camisa casual de lino para verano",
    price: 59.99,
    category: "clothing",
    stock: 35,
    images: ["/images/product-ph.png"],
    rating: 4.3,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Traje Formal",
    description: "Traje de dos piezas en lana italiana",
    price: 399.99,
    category: "clothing",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Blazer Ejecutivo",
    description: "Blazer formal para mujer",
    price: 129.99,
    category: "clothing",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sudadera con Capucha",
    description: "Sudadera deportiva unisex",
    price: 49.99,
    category: "clothing",
    stock: 45,
    images: ["/images/product-ph.png"],
    rating: 4.4,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Home
  {
    name: "Sofá Modular",
    description: "Sofá en L con tapizado premium",
    price: 999.99,
    category: "home",
    stock: 5,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mesa de Centro",
    description: "Mesa de centro de diseño escandinavo",
    price: 299.99,
    category: "home",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Lámpara de Pie",
    description: "Lámpara moderna con luz LED",
    price: 149.99,
    category: "home",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.4,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Juego de Sábanas",
    description: "Sábanas de algodón egipcio 1000 hilos",
    price: 89.99,
    category: "home",
    stock: 30,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Robot Aspirador",
    description: "Aspiradora robótica inteligente",
    price: 299.99,
    category: "home",
    stock: 12,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Sports
  {
    name: "Bicicleta de Montaña",
    description: "Bicicleta todo terreno profesional",
    price: 799.99,
    category: "sports",
    stock: 8,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Set de Pesas",
    description: "Kit de pesas ajustables 20kg",
    price: 199.99,
    category: "sports",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Raqueta de Tenis",
    description: "Raqueta profesional de grafito",
    price: 159.99,
    category: "sports",
    stock: 20,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Balón de Fútbol",
    description: "Balón oficial tamaño profesional",
    price: 49.99,
    category: "sports",
    stock: 40,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Tabla de Surf",
    description: "Tabla de surf para principiantes",
    price: 399.99,
    category: "sports",
    stock: 10,
    images: ["/images/product-ph.png"],
    rating: 4.4,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Otros
  {
    name: "Kit de Jardinería",
    description: "Set completo de herramientas de jardín",
    price: 79.99,
    category: "garden",
    stock: 25,
    images: ["/images/product-ph.png"],
    rating: 4.5,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Set de Arte Profesional",
    description: "Kit de pintura y dibujo artístico",
    price: 129.99,
    category: "art",
    stock: 15,
    images: ["/images/product-ph.png"],
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Telescopio Astronómico",
    description: "Telescopio refractor con trípode",
    price: 299.99,
    category: "hobby",
    stock: 8,
    images: ["/images/product-ph.png"],
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Drone con Cámara 4K",
    description: "Drone profesional con estabilizador",
    price: 699.99,
    category: "electronics",
    stock: 10,
    images: ["/images/product-ph.png"],
    rating: 4.6,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Piano Digital",
    description: "Piano eléctrico con 88 teclas pesadas",
    price: 799.99,
    category: "music",
    stock: 6,
    images: ["/images/product-ph.png"],
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Eliminar productos existentes
db.products.deleteMany({});

// Insertar nuevos productos
db.products.insertMany(sampleProducts);

print("¡Datos de productos insertados exitosamente!");
